### ISSUE TITLE
I want to make background transparent

### ISSUE THREAD

**Issue by giangpro93** [madhex/soundcloud-fb2k-waveform-seekbar#1]
This seekbar is great. Thanks for sharing the code.
I'll appreciate it if you can make the background transparent.

**Comment by madhex** [comment]
It is possible to make background color transparent and I really wanted to add this feature initially, but there is no way in Waveform plugin to distinguish weather color was selected or not. If you leave color checkbox unselected shader simply receives default color instead of transparent.
Therefore, it is impossible to support color customization along with transparency.

To achieve your goal you can find the line #218
`float4 bgColor = panelBackgroundColor * ((0.93 - (tc.x * 0.08)) + ((tc.y * 0.1) - 0.07));`

And change it to 
`float4 bgColor = 0;`

Hope it helps.

**Comment by giangpro93** [comment]
Thanks for your response!
I've already tried this before asking. Even (0,0,0,0). It's not working. So i change it to the background color of the player to be like tranparent. But when scroll the playlist, it covers the title.
![untitled](https://cloud.githubusercontent.com/assets/19707740/15789038/85f17026-29f4-11e6-8609-560f56b6bb10.png)
I'm using Veronica 2 skin. http://slowboyfast.deviantart.com/art/VERONiCA-2-502481907
I think there are something that is missing.

**Comment by madhex** [comment]
Well, now I see. I don't think it's possible, because Waveform seekbar itself has no transparency option. I'm pretty sure this issue should be addressed to that component author, but some people already asked for this option on hydrogen, and we steel don't have it.

There is one case when transparency can work even for Waveform seekbar and Absolute Glass 3 skin uses it: http://steric.deviantart.com/art/Absolute-Glass-3-198756638
(I thought you were using something like this)
As you see there is no client area in window and GUI is drawn on _window chrome_ (that glass-like stuff), that's the key.

I played a bit with Veronica skin and here is the same result:
![2467502346592](https://cloud.githubusercontent.com/assets/3943889/15794451/74c3c91c-29f3-11e6-9858-e793704b9bf4.png)

background is transparent only on draggable area that relates to window chrome.

So, there is no way to achieve this modifying only shader. Sorry.

**Comment by giangpro93** [comment]
I don't know how the render work. I think simple that if we not output this pixel, it'll not appear. Are there any ways to do that?

**Comment by madhex** [comment]
Shaders process each pixel one by one, so you cannot just skip one, but you can leave it transparent. There is no limitation for this in shader. However, shader is only a part of whole render process and its result is combined with some other background. I'm not aware about Waveform seekbar component implementation details... it can leave its background filled, or it can pre-fill DX context with some color and mix it with shader result, or something else, I don't know. Anyway, Waveform seekbar does not support transparent background (the example with Absolute Glass 3 skin uses trick to avoid this limitation, which is not applicable for normal skins)

Again, there is no way to achieve this modifying only shader.

Your options:
1. Fork Waveform seekbar and implement component background transparency by yourself.
2. Revise your skin and use something else. For example, Channel spectrum panel supports transparent background explicitly (it's not a seekbar).
